# Generated by Django 4.2 on 2024-12-11 21:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("user_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
