# Generated by Django 4.2 on 2024-12-12 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
