# Generated by Django 4.2 on 2024-12-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("broker", "Broker"), ("admin", "Admin")],
                default="buyer",
                help_text="Роль пользователя в системе",
                max_length=20,
            ),
        ),
    ]
