# Generated by Django 4.2 on 2024-12-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Главный администратор"),
                    ("admin", "Администратор"),
                    ("moderator", "Модератор"),
                    ("ambassador", "Амбассадор"),
                    ("broker", "Брокер"),
                    ("buyer", "Покупатель"),
                ],
                default="buyer",
                help_text="Роль пользователя в системе",
                max_length=20,
            ),
        ),
    ]
