# Generated by Django 4.2 on 2024-12-12 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_userprofile_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
