# Generated by Django 4.2 on 2024-12-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="catalog",
        ),
        migrations.AddField(
            model_name="object",
            name="land_area",
            field=models.FloatField(
                blank=True, help_text="Площадь участка, кв.м", null=True
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="living_area",
            field=models.FloatField(
                blank=True, help_text="Жилая площадь, кв.м", null=True
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="rooms",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
