# Generated by Django 4.2 on 2024-12-11 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0002_remove_object_catalog_object_land_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="broker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalogs",
                related_query_name="catalog",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
