# Generated by Django 4.2 on 2024-12-11 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0003_alter_catalog_broker"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Object",
            new_name="RealEstateObject",
        ),
    ]
