# Generated by Django 4.2 on 2024-12-11 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0004_rename_object_realestateobject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestateobject",
            name="broker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="real_estate_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
