# Generated by Django 4.2 on 2024-12-16 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0006_alter_realestateobject_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestateobject",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Кто назначил брокера на объект",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="realestateobject",
            name="complex_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
